name: faulkner_n0
description: Hacking / Security / Thoughts / Learnings
meta_description: "faulkner_n0 | Hacking / Security / Thoughts / Learnings"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: ' faulkner-n0.com'
google_analytics: 'UA-168741590-1'
#gems: [jekyll-paginate]

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
# Details for the RSS feed generator
url:            'https://faulkner-n0.com'
author:         'faulkner_n0'
